name: Launch EC2 Instance

on:
  workflow_dispatch:  # manual trigger

jobs:
  launch-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.ap-south-1 }}

      - name: Launch EC2 instance
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-02d26659fd82cf299 \
            --instance-type t2.micro \
            --key-name pemfile \
            --security-group-ids sg-0853bebc817d9aa38 \
            --subnet-id subnet-0710333307521dbe3 \
            --query 'Instances[0].InstanceId' \
            --output text)

          echo "Launched EC2 Instance with ID: $INSTANCE_ID"

